sprint-6/step-1: Задачи спринта #6
kudya/practicum-react-burger pull request #6
Opened 2024-03-17 14:18 UTC by kudya

- Добавлены тесты по редьюсерам

2024-03-18 20:46 UTC, kudya commented
- Добавлены cypress тесты для ключевой логики приложения

2024-03-19 03:55 UTC, kudya commented
- Подготовка файла Readme (без ссылки на деплой)

2024-03-19 05:00 UTC, kudya commented
- добавление информации о ссылке на страницу с деплоем приложения

2024-03-19 05:46 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все юнит-тесты проходят успешно
- Все Cypress тесты проходят успешно
- В readme есть ссылка на проект.

### **Есть несколько замечаний, которые нужно исправить:**

- По чек-листу, вам нужно добавить cypress тест для проверки открытия модального окна с данными о заказе при клике по кнопке «Оформить заказ»

- Отметил небольшое замечание в коде;

### **Сделает код лучше:**

- Рекомендую добавить команду в `package.json` для открытия cypres: `"cypress:open": "./node_modules/.bin/cypress open"`, так намного удобнее запускать cypress.;

- Чтобы проверить процент покрытия тестами всех файлов, используйте команду `react-scripts test --coverage --watchAll`

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>;

2024-03-19 05:46 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.js
> +        cy.visit('http://localhost:3000');
**Надо исправить:**

Здесь и далее.

лучше вынести базовый адрес сервера в конфиг cypress.

<https://docs.cypress.io/guides/references/best-practices#Setting-a-Global-baseUrl>

2024-03-19 05:46 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.js
> +        cy.intercept('GET', 'ingredients', {fixture: 'ingredients'})
**Вы молодец:**

круто что мокаете запросы

2024-03-19 13:57 UTC, kudya commented on cypress/e2e/constructor.cy.js
> +        cy.visit('http://localhost:3000');
- baseUrl вынесено в конфиг
- спасибо за подсказку такого паттерна - так намного удобнее и нагляднее, особенно, если продолжать писать ui-тесты не только по главной странице

2024-03-19 14:13 UTC, kudya commented
@ArslanMustafin 
Спасибо за подробную обратную связь!

Правки по код-ревью:

1. "лучше вынести базовый адрес сервера в конфиг cypress": скорректировано, в ревью отписано и помечено, как resolved

2. "По чек-листу, вам нужно добавить cypress тест для проверки открытия модального окна с данными о заказе при клике по кнопке «Оформить заказ»": наставник на вебинарах отмечал, что данное задание не будет относиться к обязательным плюс позже подтверждал данный момент - поэтому,  по согласованию с куратором (Александра Трошина), данный пункт в проектной работе можно не считать критичным для приёма проекта

2024-03-19 14:37 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкасты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2024-03-19 14:58 UTC, merged